obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.18
inflation_radius: 0.20
observation_sources: "base_laser_cloud"
base_laser_cloud:
  data_type: PointCloud
  topic: /base_cloud
  marking: true
  clearing: true
